spring.application.name=api-loja

spring.datasource.url=jdbc:postgresql://localhost:5432/loja_db
spring.datasource.username=postgres
spring.datasource.password=Dae123457*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true